### PR TITLE
Issue #186 Force str type for HTTP header fields.

### PR DESCRIPTION
**Pull request by serac**
Candidate fix for #186.

### CODE REVIEW

**Comment by rohe** [comment]
Well, this breaks a number of tests so I can't let it in.
We'll have to fix that first.

**Comment by serac** [comment]
Understood. Do you agree with the premise that header field names/values ought to be ASCII strings?

**Comment by rohe** [comment]
Well, by default message (RFC 2616, 5987) header fields in HTTP can not carry characters outside the ISO 8859-1 character set. So yes !

**Comment by serac** [comment]
Ok, that was my analysis as well.

**Comment by lwm** [comment]
@serac, any update on this? Would be nice to get this merged soon!

**Comment by lwm** [comment]
Well, that says it all :smile:

**Pull request closed without merging**
