### PR TITLE
Add build support for appveyor

### LINKED ISSUE #409: Add AppVevor build for Windows support
https://www.appveyor.com/

We should probably do that. I see a number of issues reported on the windows platform.

This CI build might smoke out anything stupid we might do :)

### PR DESCRIPTION
**Pull request by tpazderka**
Close #409

FIXME: Update image build URL after authorization

- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
---

### CODE REVIEW

**Comment by lwm** [comment]
It's starting! Windowwwsss is comminnngggg

**Comment by tpazderka** [comment]
And now it's not working... :(

**Comment by tpazderka** [comment]
I will try a new PR...

**Comment by tpazderka** [comment]
I guess I will merge it and we will tweak the settings later...

**Pull request closed without merging**
