### PR TITLE
Skip keys of types that are not know or where the key is poorly speci…

### PR DESCRIPTION
**Pull request by rohe**
…fied.

The import method will now skip keys the system can't use instead of throwing an exception.

Thanks for contributing to this library! Please include the following check
list in your pull request submission (you can delete this message). If your
changes don't need a change log or documentation update, please ignore this.

- [X] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.

---

### CODE REVIEW

**Comment by zandbelt** [comment]
I'd like to see this one go into the next pyoidc release but I guess CI needs to be fixed first...?

**Comment by tpazderka** [comment]
@rohe Do you have time to work on this or should I take over?

**Comment by rohe** [comment]
If you have time in the next couple of days please go ahead. I can't do anything until next week.

**Comment by tpazderka** [comment]
OK, will do.

**Comment by tpazderka** [comment]
Closing in favor of #485

**Pull request closed without merging**
