### PR TITLE
Fix MutableMapping deprecation warning

### PR DESCRIPTION
**Pull request by zhelyabuzhsky**
- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
- [ ] New code is annotated.
- [ ] Changes are covered by tests.
---

### CODE REVIEW

**Comment by tpazderka** [comment]
Thanks for your contribution!

Merged by hand.

**Comment by zhelyabuzhsky** [comment]
> Merged by hand.

why not with GitHub "merge" button? =)

**Comment by tpazderka** [comment]
To have jus tone commit in there :)

**Comment by schlenk** [comment]
github offers a "squash commits" options in the merge button...

**Comment by tpazderka** [comment]
Yeah, but it sometimes does fast-forward merge... :(

**Pull request closed without merging**
