### PR TITLE
Add delay to link checker

### PR DESCRIPTION
**Pull request by tpazderka**
It was getting HTTP 429 code from github.

- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
- [ ] New code is annotated.
- [ ] Changes are covered by tests.
---

### CODE REVIEW

**Comment by tpazderka** [comment]
Bandit is also complaining about `shelve`. Should we drop the module or just ignore bandit on this one?

I personally do not use it and I am not sure how widespread it might be...

**Comment by schlenk** [comment]
I think shelve is just used, because it is in the python stdlib. No issues with replacing it.

**Review by schlenk — APPROVED** [review]
LGTM

**Comment by schlenk** [comment]
Looks ok.

**Pull request merged**
