### PR TITLE
Support for dict in Client.parse_response formats

### PR DESCRIPTION
**Pull request by Hultner**
- [x] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [x] The documentation has been updated, if necessary.
- [x] New code is annotated.
- [x] Changes are covered by tests.
---
In response to #789

### CODE REVIEW

**Review by schlenk — COMMENTED** [review]
It seems line 630ff in parse_response() needs some cast() to make mypy happy for the urlencoded path still.

```
        if sformat == "urlencoded":
            str_info = cast(str, info)
            info = self.get_urlinfo(str_info)
```

Looks good otherwise. Could you add this please?

**Comment by Hultner** [comment]
> It seems line 630ff in parse_response() needs some cast() to make mypy happy for the urlencoded path still.
> 
> ```
>         if sformat == "urlencoded":
>             str_info = cast(str, info)
>             info = self.get_urlinfo(str_info)
> ```
> 
> Looks good otherwise. Could you add this please?

Fixed it now. I also added an additional type guard so that an error is raised if info is passed as an dict but sformat isn't a dictionary.

**Review by schlenk — APPROVED** [review]
Seems the extra isinstance() check pushes pylama over the threshold of its complexity measure due to the extra if. I just pushed the limit a little higher as it is arbitrary anyway and will refactor it later. 

The Travis check is basically dead (due to travis stopping its free service), so no issue there.

**Comment by Hultner** [comment]
> Seems the extra isinstance() check pushes pylama over the threshold of its complexity measure due to the extra if. I just pushed the limit a little higher as it is arbitrary anyway and will refactor it later.
> 
> The Travis check is basically dead (due to travis stopping its free service), so no issue there.
Thanks for the swift feedback and process :) 

I saw that the last release was last year. Is there any plan for when the next release will be? I've seen some other changes in master which aren't in the released version which I'd like to have.

**Comment by schlenk** [comment]
Yes, a release is planned soonish, i think when @tpazderka finds the time to do one.

**Comment by Hultner** [comment]
Nice, great to hear. Looks like you've made some python 3.9 improvements since the last release.

**Pull request merged**
