### PR TITLE
Decrease complexity of authn/saml.py

### PR DESCRIPTION
**Pull request by tpazderka**
- [x] Any changes relevant to users are recorded in the `CHANGELOG.md`.

---
Ref #311

### CODE REVIEW

**Comment by lwm** [comment]
Hey, I thought we were going to make these small!? A 300+ line diff is not easy to review ;)

**Comment by tpazderka** [comment]
The only change is that the `try: except` moved to the top and everything got dedented...

**Comment by tpazderka** [comment]
I do recommend doing the review from cmommandline using `git diff --ingore-space-change` :)

**Comment by lwm** [comment]
Ah yes, thanks (didn't know about that option!)! Yes, I agree with this change, LGTM :+1:

**Pull request merged**
