### PR TITLE
Use Codecov instead of coveralls

### PR DESCRIPTION
**Pull request by tpazderka**
- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
---

### CODE REVIEW

**Comment by tpazderka** [comment]
@rohe Can you please login to Codecov and try to enable either the Webhook or the Plugin?

We can try both and see what suits us better.

**Comment by lwm** [comment]
Nice one!

**Comment by tpazderka** [comment]
If that wasn't you Roland, then there is probably nothing else to do. It seems that Codecov reuses the comment and is not creating a new every time. I will try that tomorrow with couple of rebases...

**Comment by tpazderka** [comment]
It looks like it works! :)

**Comment by tpazderka** [comment]
OK guys, I think that this one looks much better than coveralls. The comment is reused so no spamming and the report is also more useful as it shows coverage change for changed files.

So if noone has any objections, I would like to merge this.

**Comment by lwm** [comment]
go go go go go go go go go go go go

**Comment by lwm** [comment]
For discovery, this deals with what we discussed in https://github.com/OpenIDC/pyoidc/issues/404.

**Comment by tpazderka** [comment]
Yes :)

**Pull request merged**
