### PR TITLE
make phone_number_verified a boolean in OpenIDSchema

### PR DESCRIPTION
**Pull request by zandbelt**
addresses OpenIDC/pyoidc#407

### CODE REVIEW

**Comment by lwm** [comment]
That's awesome that you put time on this one @zandbelt! Could I ask you to write a test for this? It might seem really boring but one line changes always scare me. Especially when the other tests pass ;)

**Comment by rohe** [comment]
I definitely support this change, it's really fixing a bug.
But @lwm is right we should add a test.

**Comment by rohe** [comment]
Wrote a couple of tests. They showed a bug in the code. Will submit a PR.

**Comment by lwm** [comment]
Thanks @rohe, will close off this PR for #418 (this change set merged there). 

Thanks for contributing @zandbelt!

**Pull request closed without merging**
