### PR TITLE
Try Github actions

### PR DESCRIPTION
**Pull request by tpazderka**
Ref #770

- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
- [ ] New code is annotated.
- [ ] Changes are covered by tests.
---

### CODE REVIEW

**Comment by tpazderka** [comment]
Seems to be mostly working. I will switch to python images and all pythons next week

**Comment by schlenk** [comment]
Any progress on this?

**Comment by tpazderka** [comment]
Eh, sorry for the delay. I think it should be done now.

**Comment by schlenk** [comment]
The shelve stuff can probably be fixed with some #nosec comments, but thats not important for the start.

**Review by schlenk — APPROVED** [review]
LGTM.

**Pull request merged**
