### PR TITLE
Removed unused variables

### PR DESCRIPTION
**Pull request by tpazderka**
Part 2 of #298

### CODE REVIEW

**Comment by lwm** [comment]
Uhh, are all these changes in https://github.com/OpenIDC/pyoidc/pull/307?

**Comment by tpazderka** [comment]
Yes, the branches sit on top of each other.
I will rebase them.

**Comment by tpazderka** [comment]
@lwm The branch is now clean again :)

**Comment by lwm** [comment]
Well done. LGTM :+1:

**Pull request merged**
