### PR TITLE
Optimize tox and travis

### PR DESCRIPTION
**Pull request by tpazderka**
- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
---
- Using matrix only when absolutely neccessary
- Do not use pipenv for installation, it duplicates tox setup and package installation (it looks like it shortens a total runtime by 25%)

### CODE REVIEW

**Comment by lwm** [comment]
Well done!

I am not sure I understand the 'use matrix only when necessary' commit though.

Removing the `pyenv run` from the make targets goes against my initial reasoning for when using the targets when hacking - you just run `make foo` and don't need to know about pipenv. I'm open to this new approaches, but we should decide on one - some of the targets still have the `pipenv run` prefix.

**Comment by tpazderka** [comment]
The python 3.5 is special as it needs to be run under pyhton3.5 the rest runs just fine with 3.6 so I used the env for the rest.

I do agree... what we can do is to separate the Makefile and the tox setup, the Makefile can still have the pipenv and the tox would have explicit commands not using Makefile?

**Comment by lwm** [comment]
Ah, right! Yep, sounds good to me, nice one!

**Comment by tpazderka** [comment]
OK, i will update the PR shortly :)

**Comment by tpazderka** [comment]
Updated

**Pull request merged**
