### PR TITLE
Rely solely on Tox for environment testing.

### PR DESCRIPTION
**Pull request by lwm**
Hacking on something for https://github.com/OpenIDC/pyoidc/issues/301.

### CODE REVIEW

**Comment by tpazderka** [comment]
This [commit[(https://github.com/OpenIDC/pyoidc/commit/45a4971379f64212a78ef8852e7373a0fa4cfdca) probably solves the issues we are having...

**Comment by lwm** [comment]
Thanks @tpazderka, I've adapted that change in https://github.com/OpenIDC/pyoidc/pull/302/commits/401dfcbf13783d306a2d9e32e8da24f0b22deec6. Hoping for a green build soon :)

**Comment by tpazderka** [comment]
@lwm Sorry for the conflicts...
I say we dump the `3.5` but otherwise go with your changes...

**Comment by lwm** [comment]
> @lwm Sorry for the conflicts...

No worries!

> I say we dump the 3.5 but otherwise go with your changes...

I'm quite stubborn ;) I'll try some more ... I think a lot of people use this version.

**Comment by lwm** [comment]
OK, I give up :)

**Pull request merged**
