### PR TITLE
Assure fresh IV for CookieDealer

### PR DESCRIPTION
**Pull request by lwm**
- [x] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] ~~The documentation has been updated, if necessary.~~

---

Closes https://github.com/OpenIDC/pyoidc/issues/363.

### CODE REVIEW

**Comment by lwm** [comment]
Oh! If the CookieDealer creates a cookie, it can parse it afterwards (because it stores the seed and IV on the class). However, if the CookieDealer creates two cookies, it can only parse the second one and not the first (because this change generates new seed/IV values).

What's to be done about that?

**Comment by schlenk** [comment]
@lvm The same as always with IV's. Those are called IVs and not keys for a reason, IVs do not need to be kept not secret, so you can simply prepend them to the message. So just prefix the cookie contents with the IV. (the SymKeyAuthn does that already).

**Comment by lwm** [comment]
Oof, actually, making this change is pretty serious (mega test failure). I'll leave this for now.

**Comment by schlenk** [comment]
Ok, I'll have a look at it hopefully soon. There are some other things that should be done better with cookie encryption (e.g. AEAD encryption instead of simple AES-CBC to prevent attackers messing with message integrity).

**Pull request closed without merging**
