### PR TITLE
Fix for black update

### PR DESCRIPTION
**Pull request by tpazderka**
- [ ] Any changes relevant to users are recorded in the `CHANGELOG.md`.
- [ ] The documentation has been updated, if necessary.
- [ ] New code is annotated.
- [ ] Changes are covered by tests.
---

### CODE REVIEW

**Comment by schlenk** [comment]
Seems the Py3.5 stuff is hit by the cryptography update (https://cryptography.io/en/latest/faq/#faq-howto-handle-deprecation-warning).

**Comment by tpazderka** [comment]
Yes, I will go over it on Monday and clean that up.

**Review by schlenk — APPROVED** [review]
LGTM. Feel free to merge once travis likes it.

**Comment by tpazderka** [comment]
Had to add missing library to integration tests but is is now finally passing :)

**Review by schlenk — APPROVED** [review]

**Pull request merged**
