### PR TITLE
Use pipenv to manage dependencies

### PR DESCRIPTION
**Pull request by lwm**
Benefits:
  * Remove crazy (in hindsight) Makefile/pip-tools dependency management
  * Let pipenv manage virtual environments, pinning, upgrades and development installs.

~~Might need a few takes to get it working with CI.~~

In my mind, a far superior arrangement. You just need to run `pipenv install --dev` and prefix your commands with `pipenv run` or operate inside a `pipenv shell` to work with the library in development.

Let me know what you all think.

### CODE REVIEW

**Comment by schlenk** [comment]
The idea sounds nice. I don't have experience with pipenv, (still stuck with buildout at work :-( ), so cannot really comment. Will give it a try.

**Comment by rohe** [comment]
I'm with Michael, I like the idea but don't know enough about pipenv.

**Comment by lwm** [comment]
So, is it the case that you all use different ways to manage your development environment? Should we just remove all methods (such as pip-tools and pipenv here) and leave it up to each developer? We could simply suggest pipenv as the default if someone is new to it all.

**Comment by schlenk** [comment]
I'm actually fine with any documented, standard way to do things. 

I usually do not have the luxury to define my 'standard' way, so I use whatever works/is already there. If it works and i can tweak things easily enough when it fails, I'm fine with it. Simple to understand is preferred to layers upon layers of distraction.

One case where i tweaked my install procedure was the pyldap package used for test, thats a mess on windows. Unless you happen to have a full openldap development installation, you cannot build pyldap, i usually just pick the prebuilt wheels that are sadly not on pypi, but available here http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyldap

'make' is usually a bad idea on Windows, due to not having a GNU make around. So pipenv is a clear improvement over that. The Makefile was easy to read though and GNU make is halfway easy to install too.

I haven't tested the pipenv things fully yet, just installed pipenv via this pipsi thing, which kind of works (even if i find it scary that the installation is more trouble than installing GNU Make and the defaults set on installation were forgotten and i needed to read the code to setup the proper environment vars as the defaults are not so nice on Windows.)

**Comment by lwm** [comment]
Well, I'm erring on merging this PR then. Pipenv is cross platform and what I would expect the new best practice to be in the coming months. I leave this open for a while longer for anyone to voice concern.

**Comment by lwm** [comment]
:bomb:

**Comment by schlenk** [comment]
Well, seems it doesn't work yet (on Windows), and pipenv is pretty unhelpful with outputs:

1. If pipenv.exe isn't in %PATH% it fails without any useful error message
2. If you do not specify --python it fails with a somewhat useful error message
3. If you do all of the above, it installs a few things, then blows up with the traceback below (on Python 2.7)
4. Reading dark blue errors on the default black console background is nearly impossible, would love to nuke the useless console colours (set PIPENV_COLORBLIND=1 kills those)
5. Rerunning it with --python c:\Python36\python.exe gets a bit further and just spews dark blue on black tracebacks of a failed pyldap compile (no wheels, see above) on the console and fails too (see Traceback 2)
6. Trying to fix it by running 'pipenv.exe shell' and installing the prebuilt wheel via pip i have fails too, because the shell spawned by pipenv is totally unusable (keyboard entry gets truncated, garbled and sent to nirvana, probably due to spawning a powershell from a cmd.exe shell from a python wrapper from a python wrapper from a python wrapper...)
7. I do only get a fancy coloured progressbar counting numbers but have no clue which packages got installed (unless i look into the venv myself)
8. Sadly there is neither a --debug nor --verbose flag for pipenv.exe either, nor does it write any kind of logfile (or doesn't tell where)

d:\code\gitrepos\pyoidc>c:\tools\bin\pipenv.exe --two --python c:\Python27_x64\python.exe install --dev
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Using c:\Python27_x64\python.exe to create virtualenv...
Running virtualenv with interpreter c:\Python27_x64\python.exe
New python executable in C:\Users\msc\.virtualenvs\pyoidc-wcZyveBj\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\msc\.virtualenvs\pyoidc-wcZyveBj
No package provided, installing all dependencies.
Pipfile found at d:\code\gitrepos\pyoidc\Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
An error occured while installing! 33/57 - 00:01:35
[================================] 33/57 - 00:02:14
Traceback (most recent call last):
  File "c:\Python27_x64\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\Python27_x64\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\tools\bin\pipenv.exe\__main__.py", line 9, in <module>
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\cli.py", line 824, in install
    do_init(dev=dev, allow_global=system, ignore_hashes=ignore_hashes, ignore_pipfile=ignore_pipfile)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\cli.py", line 607, in do_init
    ignore_hashes=ignore_hashes)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\cli.py", line 275, in do_install_dependencies
    click.echo(crayons.blue(format_pip_output(c.out)))
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\click\utils.py", line 221, in echo
    message = text_type(message)
  File "d:\code\venv\pipenv\lib\site-packages\pipenv\vendor\crayons.py", line 89, in __unicode__
    return value.decode('utf8')
  File "d:\code\venv\pipenv\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x94 in position 5650: invalid start byte

And for Python 3.6:
d:\code\gitrepos\pyoidc>c:\tools\bin\pipenv.exe --two --python c:\Python36_x64\python.exe install --dev
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Using c:\Python36_x64\python.exe to create virtualenv...
Running virtualenv with interpreter c:\Python36_x64\python.exe
Using base prefix 'c:\\Python36_x64'
New python executable in C:\Users\msc\.virtualenvs\pyoidc-wcZyveBj\Scripts\python.exe
Installing setuptools, pip, wheel...done.

Virtualenv location: C:\Users\msc\.virtualenvs\pyoidc-wcZyveBj
No package provided, installing all dependencies.
Pipfile found at d:\code\gitrepos\pyoidc\Pipfile. Considering this to be the project home.
Installing dependencies from Pipfile.lock...
An error occured while installing! 33/57 - 00:01:03
Collecting pyldap==2.4.37
  Using cached pyldap-2.4.37.tar.gz
Requirement already satisfied: setuptools in c:\users\msc\.virtualenvs\pyoidc-wczyvebj\lib\site-packages (from pyldap==2
.4.37)
Building wheels for collected packages: pyldap
  Running setup.py bdist_wheel for pyldap: started
  Running setup.py bdist_wheel for pyldap: finished with status 'error'
  Complete output from command c:\users\msc\.virtualenvs\pyoidc-wczyvebj\scripts\python.exe -u -c "import setuptools, to
kenize;__file__='C:\\Users\\msc\\AppData\\Local\\Temp\\1\\pip-build-l25bybty\\pyldap\\setup.py';f=getattr(tokenize, 'ope
n', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d
C:\Users\msc\AppData\Local\Temp\1\tmp3t7gm43qpip-wheel- --python-tag cp36:
  defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R
  extra_compile_args:
  extra_objects:
  include_dirs: /usr/include /usr/include/sasl /usr/local/include /usr/local/include/sasl
  library_dirs: /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64
  libs: ldap_r
  running bdist_wheel
  running build
  running build_py
  file Lib\ldap.py (for module ldap) not found
  file Lib\ldap\controls.py (for module ldap.controls) not found
  file Lib\ldap\extop.py (for module ldap.extop) not found
  file Lib\ldap\schema.py (for module ldap.schema) not found
  creating build\lib.win-amd64-3.6
  copying Lib\ldapurl.py -> build\lib.win-amd64-3.6
  copying Lib\ldif.py -> build\lib.win-amd64-3.6
  copying Lib\dsml.py -> build\lib.win-amd64-3.6
  copying Lib\slapdtest.py -> build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\__init__.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\async.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\compat.py -> build\lib.win-amd64-3.6\ldap
  creating build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-3.6\ldap\controls
  copying Lib\ldap\cidict.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\dn.py -> build\lib.win-amd64-3.6\ldap
  creating build\lib.win-amd64-3.6\ldap\extop
  copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-3.6\ldap\extop
  copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-3.6\ldap\extop
  copying Lib\ldap\filter.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\functions.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\logger.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\modlist.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\resiter.py -> build\lib.win-amd64-3.6\ldap
  copying Lib\ldap\sasl.py -> build\lib.win-amd64-3.6\ldap
  creating build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\models.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-3.6\ldap\schema
  copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-3.6\ldap
  file Lib\ldap.py (for module ldap) not found
  file Lib\ldap\controls.py (for module ldap.controls) not found
  file Lib\ldap\extop.py (for module ldap.extop) not found
  file Lib\ldap\schema.py (for module ldap.schema) not found
  running egg_info
  writing Lib\pyldap.egg-info\PKG-INFO
  writing dependency_links to Lib\pyldap.egg-info\dependency_links.txt
  writing requirements to Lib\pyldap.egg-info\requires.txt
  writing top-level names to Lib\pyldap.egg-info\top_level.txt
  file Lib\ldap.py (for module ldap) not found
  file Lib\ldap\controls.py (for module ldap.controls) not found
  file Lib\ldap\extop.py (for module ldap.extop) not found
  file Lib\ldap\schema.py (for module ldap.schema) not found
  reading manifest file 'Lib\pyldap.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'Makefile'
  warning: no files found matching 'Modules\LICENSE'
  writing manifest file 'Lib\pyldap.egg-info\SOURCES.txt'
  running build_ext
  building '_ldap' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\Modules
  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSI
ON=2.4.37 -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -Ic:\Python36_x64\
include -Ic:\Python36_x64\include /TcModules/LDAPObject.c /Fobuild\temp.win-amd64-3.6\Release\Modules/LDAPObject.obj
  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------
  Running setup.py clean for pyldap
Failed to build pyldap
Installing collected packages: pyldap
  Running setup.py install for pyldap: started
    Running setup.py install for pyldap: finished with status 'error'
    Complete output from command c:\users\msc\.virtualenvs\pyoidc-wczyvebj\scripts\python.exe -u -c "import setuptools,
tokenize;__file__='C:\\Users\\msc\\AppData\\Local\\Temp\\1\\pip-build-l25bybty\\pyldap\\setup.py';f=getattr(tokenize, 'o
pen', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --rec
ord C:\Users\msc\AppData\Local\Temp\1\pip-q6hc70sa-record\install-record.txt --single-version-externally-managed --compi
le --install-headers c:\users\msc\.virtualenvs\pyoidc-wczyvebj\include\site\python3.6\pyldap:
    defines: HAVE_SASL HAVE_TLS HAVE_LIBLDAP_R
    extra_compile_args:
    extra_objects:
    include_dirs: /usr/include /usr/include/sasl /usr/local/include /usr/local/include/sasl
    library_dirs: /usr/lib /usr/lib64 /usr/local/lib /usr/local/lib64
    libs: ldap_r
    running install
    running build
    running build_py
    file Lib\ldap.py (for module ldap) not found
    file Lib\ldap\controls.py (for module ldap.controls) not found
    file Lib\ldap\extop.py (for module ldap.extop) not found
    file Lib\ldap\schema.py (for module ldap.schema) not found
    creating build\lib.win-amd64-3.6
    copying Lib\ldapurl.py -> build\lib.win-amd64-3.6
    copying Lib\ldif.py -> build\lib.win-amd64-3.6
    copying Lib\dsml.py -> build\lib.win-amd64-3.6
    copying Lib\slapdtest.py -> build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\__init__.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\async.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\compat.py -> build\lib.win-amd64-3.6\ldap
    creating build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\__init__.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\deref.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\libldap.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\openldap.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\ppolicy.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\psearch.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\pwdpolicy.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\readentry.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\sessiontrack.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\simple.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\controls\sss.py -> build\lib.win-amd64-3.6\ldap\controls
    copying Lib\ldap\cidict.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\dn.py -> build\lib.win-amd64-3.6\ldap
    creating build\lib.win-amd64-3.6\ldap\extop
    copying Lib\ldap\extop\__init__.py -> build\lib.win-amd64-3.6\ldap\extop
    copying Lib\ldap\extop\dds.py -> build\lib.win-amd64-3.6\ldap\extop
    copying Lib\ldap\filter.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\functions.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\ldapobject.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\logger.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\modlist.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\resiter.py -> build\lib.win-amd64-3.6\ldap
    copying Lib\ldap\sasl.py -> build\lib.win-amd64-3.6\ldap
    creating build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\__init__.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\models.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\subentry.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\schema\tokenizer.py -> build\lib.win-amd64-3.6\ldap\schema
    copying Lib\ldap\syncrepl.py -> build\lib.win-amd64-3.6\ldap
    file Lib\ldap.py (for module ldap) not found
    file Lib\ldap\controls.py (for module ldap.controls) not found
    file Lib\ldap\extop.py (for module ldap.extop) not found
    file Lib\ldap\schema.py (for module ldap.schema) not found
    running egg_info
    writing Lib\pyldap.egg-info\PKG-INFO
    writing dependency_links to Lib\pyldap.egg-info\dependency_links.txt
    writing requirements to Lib\pyldap.egg-info\requires.txt
    writing top-level names to Lib\pyldap.egg-info\top_level.txt
    file Lib\ldap.py (for module ldap) not found
    file Lib\ldap\controls.py (for module ldap.controls) not found
    file Lib\ldap\extop.py (for module ldap.extop) not found
    file Lib\ldap\schema.py (for module ldap.schema) not found
    reading manifest file 'Lib\pyldap.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'Makefile'
    warning: no files found matching 'Modules\LICENSE'
    writing manifest file 'Lib\pyldap.egg-info\SOURCES.txt'
    running build_ext
    building '_ldap' extension
    creating build\temp.win-amd64-3.6
    creating build\temp.win-amd64-3.6\Release
    creating build\temp.win-amd64-3.6\Release\Modules
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VER
SION=2.4.37 -IModules -I/usr/include -I/usr/include/sasl -I/usr/local/include -I/usr/local/include/sasl -Ic:\Python36_x6
4\include -Ic:\Python36_x64\include /TcModules/LDAPObject.c /Fobuild\temp.win-amd64-3.6\Release\Modules/LDAPObject.obj
    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------

  Failed building wheel for pyldap
Command "c:\users\msc\.virtualenvs\pyoidc-wczyvebj\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\U
sers\\msc\\AppData\\Local\\Temp\\1\\pip-build-l25bybty\\pyldap\\setup.py';f=getattr(tokenize, 'open', open)(__file__);co
de=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\msc\AppData
\Local\Temp\1\pip-q6hc70sa-record\install-record.txt --single-version-externally-managed --compile --install-headers c:\
users\msc\.virtualenvs\pyoidc-wczyvebj\include\site\python3.6\pyldap" failed with error code 1 in C:\Users\msc\AppData\L
ocal\Temp\1\pip-build-l25bybty\pyldap\

[================================] 33/57 - 00:01:23

**Pull request merged**
